name: Telegram Commit Alert

on:
  push:
    branches:
      - main
      - develop
      - deploy  # Add any other branches you want alerts for

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram commit alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          # Get commit details
          COMMIT_DETAILS=$(git log -1 --pretty=format:"• Author: %an%n• Email: %ae%n• Commit ID: %H%n• Message: %s%n• Date: %ad" $COMMIT_SHA)
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${COMMIT_SHA}"

          # Build the Telegram message
          MESSAGE="🚀 New Commit Alert by *${GITHUB_ACTOR}* 🚀

📄 Commit Message:
  $(git log -1 --pretty=format:'%s' $COMMIT_SHA)

🌿 Branch:
  ${GITHUB_REF_NAME}

📂 Repository:
  ${GITHUB_REPOSITORY}

🔗 View Commit:
  [Click here to see the changes](${COMMIT_URL})

🕒 Timestamp:
  $(git log -1 --pretty=format:'%cI' $COMMIT_SHA)

📝 Commit Details:
  ${COMMIT_DETAILS}"
  
  # Send the message to Telegram
  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
  -d chat_id=${TELEGRAM_CHAT_ID} \
  -d parse_mode=Markdown \
  -d text="$MESSAGE"
